---
- hosts: all
  gather_facts: no

  vars_prompt:
  - name:   new_db_user
    prompt: Database User (e.g. something_user)
    private: no
  - name:    new_db_pass
    prompt:  Password for Database User
    private: yes
    confirm: yes

  pre_tasks:
    - include: tasks/db-user.yml
    - set_fact: new_db_user={{ new_db_user }} new_db_pass={{ new_db_pass }}
