---
ruby_version:    2.2.3
nvm_version:     v0.26.1
nodejs_version:  v0.12.7
phpunit_version: ~4.8

nvm_root:   /usr/local/nvm
rbenv_root: /usr/local/rbenv

ansible_python_interpreter: /usr/bin/python2
