---
- name: Re-enable Root User in Production
  hosts: production

  vars_prompt:
    - name: ansible_sudo_pass
      prompt: Sudo Password
      private: yes

  tasks:
    - name: Enable root User
      command: passwd -u root
      become: true

    - name: Allow root SSH Login
      lineinfile:
        dest:   /etc/ssh/sshd_config
        state:  present
        regexp: "^{{ item.key }}"
        line:   "{{ item.key }} {{ item.value }}"
      with_items:
        - { key: 'PermitRootLogin', value: 'yes' }
        - { key: 'AllowUsers',      value: '{{ ansible_user_id }} root' }
      notify: Restart SSH
      become: true

  handlers:
    - name: Restart SSH
      service: name=ssh state=restarted
      become: true

