---
- name: Create Swap Space
  command: fallocate -l 1G /swap
  become: true
  when: ansible_swaptotal_mb < 1023
  notify: Turn on Swap

- name: Make Swap
  command: mkswap /swap
  become: true
  when: ansible_swaptotal_mb < 1023
  notify: Turn on Swap

- name: Add Swap to Fstab
  lineinfile:
    dest:   /etc/fstab
    regexp: "swap"
    line:   "/swap none swap sw 0 0"
    state:  present
  become: true
  notify: Turn on Swap
