---
- include: ../../../prompts/dev-domain.yml

- name: Create Dynamic PHP Site
  hosts: codeup-vm

  roles:
    - role: bbatsche.Codeup-PHP
      dynamic_php: yes

    ##############################################################
    ##       ULTRA TOP SECRET PHP 7 INSTALL! OMGWTFBBQ!!!       ##
    ##############################################################
    ## Comment out the role entry above                         ##
    ## Uncomment the lines below                                ##
    ## Create PHP sites like you would normally                 ##
    ## Be patient! PHP 7 is compiled from source the first time ##

    # - role: bbatsche.Phpenv
    #   dynamic_php: yes
    #   php_version: 7.0.4
    #   xdebug_version: 2.4.0
    #   phpunit_version: ~5.2
    #   pecl_extensions:
    #   - name: yaml
    #     version: 2.0.0RC7
    #   - name: imagick
    #     version: 3.4.1

