---
- name: Create Dynamic PHP Site
  hosts: vagrant
  remote_user: vagrant

  vars:
    dynamic_php: yes
  vars_prompt:
    - name:    domain
      prompt:  Domain Name (e.g. codeup.test)
      private: no

  pre_tasks:
    - name: Clean domain name
      set_fact: "domain={{ domain | trim | lower }}"

    - name: Development domains must end with .test
      assert:
        that: domain.endswith(".test")

    - name: Domains cannot have spaces
      assert:
        that: not domain | search("\s")

  roles:
    - PHP
