---
- name: Create Composer Directory
  file: path={{ ansible_user_dir }}/.composer state=directory

- name: Check If Psysh Is Installed
  command: test -e {{ ansible_user_dir }}/.composer/vendor/bin/psysh
  register: checkpsyshinstall
  check_mode: no
  ignore_errors: yes
  changed_when: False

- name: Install Psysh
  when: checkpsyshinstall.rc != 0
  composer:
    command: require
    arguments: psy/psysh:@stable
    working_dir: "{{ ansible_user_dir }}/.composer/"
    no_dev: no
    prefer_dist: yes
    optimize_autoloader: no
