---
- name: Install MySQL
  apt: package={{ item }} state=present
  sudo: yes
  with_items:
    - mysql-server
    - percona-toolkit

- name: Create MySQL Configuration File
  template: src=mysql.cnf.j2 dest=/etc/my.cnf
  sudo: yes
  notify:
    - Restart MySQL
