---
- name: Initializing Server
  hosts: digital_ocean
  user: root

  vars_files:
  - "vars/{{ inventory_hostname }}.yml"

  vars_prompt:
    - name: "new_user_password"
      prompt: "Codeup User Password"
      private: yes
      confirm: yes
      encrypt: "md5_crypt"
      salt_size: 7
    - name: "admin_email"
      prompt: "Notification eMail Address"
      private: no

  tasks:
  - include: init-common.yml
  - include: tasks/lockdown_full.yml
  - include: tasks/fail2ban.yml
  - include: tasks/ufw.yml
  - include: tasks/postfix.yml

  handlers:
  - include: handlers.yml
