---
  - include: tasks/timezone.yml
  - include: tasks/sysctl.yml
  - include: tasks/system_updates.yml
  - include: tasks/system_utilities.yml
  - include: tasks/mysql.yml
  - include: tasks/nginx.yml
  - include: tasks/php.yml
  - include: tasks/php_composer.yml
  - include: tasks/bash_profile.yml
