---
- name: Server initialization

  vars:
    hostname: trusty
    domain: "codeup.dev"
    admin_email: "admin@example.com"
    www_home: /vagrant/sites

  hosts: default
  user: vagrant
  sudo: true

  tasks:

  - include: tasks/timezone.yml
  - include: tasks/sysctl.yml
  - include: tasks/system_updates.yml
  - include: tasks/system_utilities.yml
  - include: tasks/mysql.yml
  - include: tasks/nginx.yml
  - include: tasks/php.yml
  - include: tasks/php_composer.yml
  - include: tasks/postfix.yml
  - include: tasks/reboot.yml

  handlers:

  - include: handlers.yml
