---
- name: Initialize Production Server
  hosts: production
  remote_user: root

  vars_prompt:
    - name: "new_user_password"
      prompt: "Codeup User Password"
      private: yes
      confirm: yes
      encrypt: "md5_crypt"
      salt_size: 7
    - name: "admin_email"
      prompt: "Notification eMail Address"
      private: no

  tasks:
  - include: tasks/init-common.yml
  - include: tasks/lockdown_full.yml
  - include: tasks/fail2ban.yml
  - include: tasks/ufw.yml
  - include: tasks/postfix.yml

  handlers:
  - include: handlers/main.yml
