---
- name: Migrate Database
  shell: /usr/bin/php {{ www_home }}/{{ production_domain }}/artisan migrate --force
  environment: "{{ env_vars | default({}) }}"
  register: migrate_result
  changed_when: '"Nothing to migrate." not in migrate_result.stdout'

- name: Don't forget to seed your database (if necessary)
  debug:
    msg: >
      ssh {{ ansible_ssh_user }}@{{ ansible_ssh_host }}
      '/usr/bin/php {{ www_home }}/{{ production_domain }}/artisan db:seed --force'
